### ISSUE TITLE
Error building atomspace

### ISSUE THREAD

**Issue by tanksha** [opencog/atomspace#1135]
Why I am getting this error while building atomspace? I have installed the latest cogutil. thanks

[  0%] Built target persist-odbc 
[  2%] Built target logger_cython 
[  2%] Built target opencog_atom_types 
[  4%] Built target persist-pg 
[ 11%] Built target truthvalue 
[ 16%] Built target atombase 
[ 19%] Built target attentionbank 
[ 30%] Built target atomcore 
[ 35%] Built target atomutils 
[ 40%] Built target clearbox 
[ 42%] Built target lambda 
[ 47%] Built target atomspace 
[ 47%] [ 47%] Built target atomspaceutils 
Built target type_constructors 
[ 47%] Built target sql-support 
[ 57%] Built target smob 
[ 59%] Built target atomspace_cython 
[ 61%] Built target dist-gearman 
[ 69%] [ 69%] Built target query 
[ 73%] [ 76%] Built target persist 
Built target zmqatoms 
Built target persist-sql 
[ 76%] Built target logger 
[ 76%] Built target PythonEval 
[ 76%] Built target PythonSCM 
[ 80%] Built target execution 
[ 83%] Built target utilities_cython 
[ 85%] [ 85%] [ 85%] [ 88%] Built target atomspace_bm 
Built target profile_bindlink 
Built target sniff 
Built target bindlink_cython 
[ 88%] Built target scheme_wrapper 
[ 90%] [ 92%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/backwardchainer/BIT.cc.o 
Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/UREConfigReader.cc.o 
[ 95%] Built target atomspace-cwrapper 
[ 95%] Building Haskell bindings. 
[ 95%] Built target haskell-atomspace-lib 
/home/feburary/opencog/atomspace/opencog/rule-engine/backwardchainer/BIT.cc: In member function ‘std::vector<opencog::AndBIT>::iterator opencog::BIT::erase(std::vector<opencog::AndBIT>::const_iterator)’: 
/home/feburary/opencog/atomspace/opencog/rule-engine/backwardchainer/BIT.cc:638:26: error: no matching function for call to ‘std::vector<opencog::AndBIT>::erase(std::vector<opencog::AndBIT>::const_iterator&)’ 
  return andbits.erase(pos); 
                          ^ 
/home/feburary/opencog/atomspace/opencog/rule-engine/backwardchainer/BIT.cc:638:26: note: candidates are: 
In file included from /usr/include/c++/4.8/vector:69:0, 
                 from /usr/include/c++/4.8/bits/random.h:34, 
                 from /usr/include/c++/4.8/random:50, 
                 from /usr/include/c++/4.8/bits/stl_algo.h:65, 
                 from /usr/include/c++/4.8/algorithm:62, 
                 from /usr/include/boost/iterator/iterator_concepts.hpp:29, 
                 from /usr/include/boost/range/concepts.hpp:20, 
                 from /usr/include/boost/range/algorithm/binary_search.hpp:15, 
                 from /home/feburary/opencog/atomspace/opencog/rule-engine/backwardchainer/BIT.cc:23: 
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = opencog::AndBIT; _Alloc = std::allocator<opencog::AndBIT>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<opencog::AndBIT*, std::vector<opencog::AndBIT> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = opencog::AndBIT*] 
     vector<_Tp, _Alloc>:: 
     ^ 
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   no known conversion for argument 1 from ‘std::vector<opencog::AndBIT>::const_iterator {aka __gnu_cxx::__normal_iterator<const opencog::AndBIT*, std::vector<opencog::AndBIT> >}’ to ‘std::vector<opencog::AndBIT>::iterator {aka __gnu_cxx::__normal_iterator<opencog::AndBIT*, std::vector<opencog::AndBIT> >}’ 
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = opencog::AndBIT; _Alloc = std::allocator<opencog::AndBIT>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<opencog::AndBIT*, std::vector<opencog::AndBIT> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = opencog::AndBIT*] 
     vector<_Tp, _Alloc>:: 
     ^ 
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   candidate expects 2 arguments, 1 provided 
/home/feburary/opencog/atomspace/opencog/rule-engine/backwardchainer/BIT.cc:639:1: warning: control reaches end of non-void function [-Wreturn-type] 
 } 
 ^ 
make[2]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/backwardchainer/BIT.cc.o] Error 1 
make[2]: *** Waiting for unfinished jobs.... 
make[1]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/all] Error 2 
make: *** [all] Error 2

**Comment by misgeatgit** [comment]
This has been fixed in https://github.com/opencog/atomspace/commit/2d199166f9a694b16db69723e36d1bac094764ac. Pull the latest version and try rebuilding.

**Comment by AmeBel** [comment]
Since there is build break on latest revision, due to architectural change, it would be advisable if you use an older revision. At least for a weak or so. Run the following command to get to revision from February 21 . Before you run the command make sure any changes you made is stashed.
```
git reset --hard 177f47dec687ca
```

**Comment by ngeiswei** [comment]
I'm afraid this fix https://github.com/opencog/atomspace/commit/2d199166f9a694b16db69723e36d1bac094764ac does not cover that error, and I can't really bypass it. @tanksha if you can update gcc that would be ideal. I'm just using standard C++11 but it's apparently not fully supported by older versions of gcc.

**Comment by ngeiswei** [comment]
I could templatize it though, and I assume gcc would choose whatever version its standard library offers. Let me know if that's still matters to you.

**Comment by tanksha** [comment]
@ngeiswei ... updated gcc for the latest version but it is still not working and I used @AmeBel suggestion ... used the older version and it builds. But Building OpenCog failed with the following error

Linking CXX executable astartest
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc: In member function ‘json_spirit::Object opencog::AtomSpacePublisherModule::tvToJSON(opencog::TruthValuePtr)’:
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:351:14: error: the value of ‘opencog::SIMPLE_TRUTH_VALUE’ is not usable in a constant expression
         case SIMPLE_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:15:22: note: ‘opencog::Type opencog::SIMPLE_TRUTH_VALUE’ is not const
 extern opencog::Type SIMPLE_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:351:14: error: the value of ‘opencog::SIMPLE_TRUTH_VALUE’ is not usable in a constant expression
         case SIMPLE_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:15:22: note: ‘opencog::Type opencog::SIMPLE_TRUTH_VALUE’ is not const
 extern opencog::Type SIMPLE_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:360:14: error: the value of ‘opencog::COUNT_TRUTH_VALUE’ is not usable in a constant expression
         case COUNT_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:16:22: note: ‘opencog::Type opencog::COUNT_TRUTH_VALUE’ is not const
 extern opencog::Type COUNT_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:360:14: error: the value of ‘opencog::COUNT_TRUTH_VALUE’ is not usable in a constant expression
         case COUNT_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:16:22: note: ‘opencog::Type opencog::COUNT_TRUTH_VALUE’ is not const
 extern opencog::Type COUNT_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:369:14: error: the value of ‘opencog::INDEFINITE_TRUTH_VALUE’ is not usable in a constant expression
         case INDEFINITE_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:17:22: note: ‘opencog::Type opencog::INDEFINITE_TRUTH_VALUE’ is not const
 extern opencog::Type INDEFINITE_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:369:14: error: the value of ‘opencog::INDEFINITE_TRUTH_VALUE’ is not usable in a constant expression
         case INDEFINITE_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:17:22: note: ‘opencog::Type opencog::INDEFINITE_TRUTH_VALUE’ is not const
 extern opencog::Type INDEFINITE_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:382:14: error: the value of ‘opencog::PROBABILISTIC_TRUTH_VALUE’ is not usable in a constant expression
         case PROBABILISTIC_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:19:22: note: ‘opencog::Type opencog::PROBABILISTIC_TRUTH_VALUE’ is not const
 extern opencog::Type PROBABILISTIC_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:382:14: error: the value of ‘opencog::PROBABILISTIC_TRUTH_VALUE’ is not usable in a constant expression
         case PROBABILISTIC_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:19:22: note: ‘opencog::Type opencog::PROBABILISTIC_TRUTH_VALUE’ is not const
 extern opencog::Type PROBABILISTIC_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:391:14: error: the value of ‘opencog::FUZZY_TRUTH_VALUE’ is not usable in a constant expression
         case FUZZY_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:18:22: note: ‘opencog::Type opencog::FUZZY_TRUTH_VALUE’ is not const
 extern opencog::Type FUZZY_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:391:14: error: the value of ‘opencog::FUZZY_TRUTH_VALUE’ is not usable in a constant expression
         case FUZZY_TRUTH_VALUE: {
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:18:22: note: ‘opencog::Type opencog::FUZZY_TRUTH_VALUE’ is not const
 extern opencog::Type FUZZY_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:400:14: error: the value of ‘opencog::GENERIC_TRUTH_VALUE’ is not usable in a constant expression
         case GENERIC_TRUTH_VALUE:
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:20:22: note: ‘opencog::Type opencog::GENERIC_TRUTH_VALUE’ is not const
 extern opencog::Type GENERIC_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:400:14: error: the value of ‘opencog::GENERIC_TRUTH_VALUE’ is not usable in a constant expression
         case GENERIC_TRUTH_VALUE:
              ^
In file included from /usr/local/include/opencog/atoms/base/Quotation.h:30:0,
                 from /usr/local/include/opencog/atomspace/AtomTable.h:39,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:38,
                 from /home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:43:
/usr/local/include/opencog/atoms/base/atom_types.h:20:22: note: ‘opencog::Type opencog::GENERIC_TRUTH_VALUE’ is not const
 extern opencog::Type GENERIC_TRUTH_VALUE;
                      ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:401:14: error: ‘NULL_TRUTH_VALUE’ was not declared in this scope
         case NULL_TRUTH_VALUE:
              ^
/home/feburary/opencog/opencog/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc:402:14: error: ‘NUMBER_OF_TRUTH_VALUE_TYPES’ was not declared in this scope
         case NUMBER_OF_TRUTH_VALUE_TYPES: {
              ^
[100%] Built target astartest
[100%] Cythonizing spatial.pyx
Linking CXX executable tangentbug_test
[100%] Built target tangentbug_test
Scanning dependencies of target spatial_cython
[100%] Building CXX object opencog/cython/opencog/CMakeFiles/spatial_cython.dir/spatial.cpp.o
make[2]: *** [opencog/cogserver/modules/events/CMakeFiles/atomspacepublishermodule.dir/AtomSpacePublisherModule.cc.o] Error 1
make[1]: *** [opencog/cogserver/modules/events/CMakeFiles/atomspacepublishermodule.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libPathFinder3D.so
[100%] Built target PathFinder3D
Linking CXX shared library spacetime.so
[100%] Built target spacetime_cython
Linking CXX shared library libpoint_memory.so
[100%] Built target point_memory
/home/feburary/opencog/opencog/build/opencog/cython/opencog/spatial.cpp:4680:18: warning: ‘PyObject* __pyx_convert_string_to_py_(const string&)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_convert_string_to_py_(const std::string &__pyx_v_s) {
                  ^
Linking CXX shared library spatial.so
[100%] Built target spatial_cython
make: *** [all] Error 2

**Comment by leungmanhin** [comment]
Reverting to an earlier commit should get it to build
```
git reset --hard fa49f90
```

**Comment by tanksha** [comment]
@leungmanhin .. can you please write the whole commit code. Thanks

**Comment by leungmanhin** [comment]
`fa49f902d76fbe50330f069252599f2f293c9d31`, in atomspace repo

**Comment by tanksha** [comment]
It works .. thanks.

**Comment by ngeiswei** [comment]
@linas you probably want to have a look at the following https://github.com/opencog/atomspace/issues/1135#issuecomment-282994475
