### ISSUE TITLE
Python: type_ctor_atomspace is inconsistent.

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#2409]
The python bindings are inconsistent with regard to this global:
so: in ` opencog/cython/PythonSCM.cc` we have
```
"from opencog.type_constructors import set_type_ctor_atomspace")
```
but in `tests/scm/scm-python-shared-atomspace.scm`
```
from opencog.utilities import get_type_ctor_atomspace
```

The getter and setter should live in the same module, not in two different ones. That module should probably NOT be `utilities`. Also PLEASE change the name to something not-insane; for example `set_current_atomspace` would work well. This is a follow-on to pull req #2398

**Comment by linas** [comment]
@noskill @vsbogd followup to #2398

**Comment by vsbogd** [comment]
They are in fact in same module: https://github.com/opencog/atomspace/blob/2c99e42c9b7f6141da942853f92ebfb39c1e642f/opencog/cython/opencog/type_constructors.pyx#L14-L21
but Python importing/exporting specifics allows using them from another module which imports `type_constructors`

**Comment by vsbogd** [comment]
Fixed by #2415

**Comment by linas** [comment]
OK, so #2415 doesn't look like a fix to me ... it looks like you've pushed around some kind of hidden bug ... since `utilities` never exported that symbol, how did that code ever work?

Or maybe utilities still exports that symbol, in which case this is not fixed.

**Comment by linas** [comment]
Closing; #2416 marks it deprecated, and #2420 changes the overall idea.  Thanks!
